### ISSUE TITLE
Error on create

### ISSUE THREAD

**Issue by hemna** [sjlongland/aioax25#12] opened 2022-07-20 18:54 UTC
Hey man,
   I am working on a webchat version of aprsd and am using the latest from github for aioax25.   Every time I startup APRSInterface I get an exception from asyncio

```
Exception in callback <Task pending name='Task-1' coro=<TCPKISSDevice._open_connection() running at /Users/i530566/devel/mine/hamradio/aioax25/aioax25/kiss.py:540> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(9)(), <TaskWakeupMethWrapper object at 0x104d8a7f0>()]>>()
handle: <Handle <Task pending name='Task-1' coro=<TCPKISSDevice._open_connection() running at /Users/i530566/devel/mine/hamradio/aioax25/aioax25/kiss.py:540> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(9)(), <TaskWakeupMethWrapper object at 0x104d8a7f0>()]>>()>
Traceback (most recent call last):
  File "/Users/i530566/.pyenv/versions/3.8.7/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
TypeError: '_asyncio.Task' object is not callable
```

Here is how I launch APRSInterface:
https://github.com/craigerl/aprsd/blob/small_refactor/aprsd/clients/kiss.py#L46-L64

**Comment by hemna** [comment] 2022-07-20 19:47
I'm also running into a problem where I send a message out the interface, but it never makes it to direwolf (over tcpkiss).  But when my radio sends a message to direwolf, I get that packet to aprsd tcpkiss, and then the packet that I had sent out to TX, then finally gets transmitted.

**Comment by sjlongland** [comment] 2022-07-22 03:32
I'll have a look when I can… right now battling a dose of China's little gift (COVID-19) so not exactly thinking 100% straight at this time.

The error message seems quite peculiar… nothing out of the ordinary in the initialisation, but clearly `asyncio` did _not_ like what it got passed in.

https://github.com/sjlongland/aioax25/blob/master/aioax25/kiss.py#L536-L540 is where the actual connection gets created; it's supposed to take a factory function as its first argument, and that factory returns a `Protocol` object.  Most of the underlying transports (TCP and serial) use the same protocol class, but subprocess transports need a separate protocol class (they have different callbacks).

This is based on code I've written for my workplace (specifically in a test kit that basically injects commands into a microcontroller's CLI), and there it works reliably.  Those machines ran Linux though (Raspberry Pi 3s I think they were with USB-RS422 serial adaptors).

`/Users` smells like MacOS X, would I be correct in guessing this is running on an Apple system?  If so, maybe I'll have to dig out my old Macbook (which runs OS X 10.6, quite dated today but I think, still supported by recent-ish Python), see if I can get Python 3.9 running on it and do some further debugging.  I'd have thought MacOS X would work, given it's actually a certified POSIX-compliant Unix variant, but there must be some little idiosyncrasy I've overlooked.

**Comment by hemna** [comment] 2022-07-22 12:09
Yes this is running on my mac laptop.  I use it for development, but I do have a linux system as well.  fwiw, I cloned the repo and tried out an older revision of the lib (ac9dd3c5bf25a42af8924392159ad13425027fd7) and this doesn't happen.   I do seem to get a lot of exceptions being logged due to different packet datatypes.  It seems that the only datatype that the lib supports and registers is the message type.

https://github.com/sjlongland/aioax25/blob/master/aioax25/aprs/message.py#L308

my setup here at home gets packets from a digipeter about 20 miles away and my own digipeter, and I often get packets that are third-party packets which seem to simply be a packet in a packet.  

I hope you feel better soon.  I've had covid twice now.  it's not fun and takes a while to get over it.

**Comment by sjlongland** [comment] 2022-07-23 05:28
If all going to plan, it might log an exception (at `debug` level), but still should return the UI frame up the stack for it to be handled separately.

The argument for showing a backtrace in the logs is to pinpoint possible bugs in recognising UI frames that _should_ be seen as valid APRS frames.  `debug` level is used so it shouldn't be visible to most applications (unless you're observing all loggers at `debug` level).

That said, not all UI frames are APRS frames (e.g. Net/ROM is delivered over UI frames), and not every APRS frame is supported, so it's not necessarily a failure if a UI frame cannot be understood -- it may be a protocol other than APRS, and so it's handed off as a UI frame.

As for differences between ac9dd3c and current HEAD: biggest change there was a re-factoring of the low-level comms to use `asyncio` directly instead of wrapping `socket` / `serialport`.  The reason for doing this is it was supposed to improve cross-platform compatibility as it didn't rely on the POSIX interfaces for asynchronous I/O.

This was discussed in the announcement for release 0.0.11: https://github.com/sjlongland/aioax25/discussions/10

I'll have to do some more research to see what could be tickling `asyncio` on MacOS X the wrong way. :-)

**Comment by hemna** [comment] 2022-07-28 17:08
Here are some examples of the Third-party frames being rejected.

```
Handling incoming frame APPOMX*>APDW16*,K4CQ-4*,WIDE1*,WIDE2-1: PID=0xf0
Payload=b'}WB4BOR-11>APZ100,TCPIP,APPOMX*::WB4BOR-12:ack2'

Handling incoming frame N2TEK-1>APMI04,K4CQ-4*,WIDE1*: PID=0xf0
Payload=b'}KD4BNQ-3>APDW14,TCPIP,N2TEK-1*:!3721.00NG08032.23W#'

```

**Comment by sjlongland** [comment] 2022-07-31 03:07
Okay, so I managed to coax my old MacBook to life and get a version of Python 3 going on it.

Python 3.6.4 on MacOS X 10.6.  It reproduces the initial problem reported:
```
ERROR    asyncio:base_events.py:1265 Exception in callback <Task pending coro=<SerialKISSDevice._open_connection() running at /Users/stuartl/projects/aioax25/aioax25/kiss.py:485> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10257cc78>()]>>()
handle: <Handle <Task pending coro=<SerialKISSDevice._open_connection() running at /Users/stuartl/projects/aioax25/aioax25/kiss.py:485> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10257cc78>()]>>()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
TypeError: '_asyncio.Task' object is not callable
```

That's running the standard unit tests, so I'll have a look and see what can be done.

**Comment by sjlongland** [comment] 2022-07-31 03:23
So this appears to be an artefact of calling `ensure_future` and passing the result to `call_soon`.  The intent was to launch a coroutine into the background, I'm still very much new to `asyncio`, having been used to Tornado in the past.

```
diff --git a/aioax25/kiss.py b/aioax25/kiss.py
index e29b502..73cbd54 100644
--- a/aioax25/kiss.py
+++ b/aioax25/kiss.py
@@ -421,7 +421,7 @@ class BaseTransportDevice(BaseKISSDevice):
         raise NotImplementedError('Abstract function')
 
     def _open(self):
-        self._loop.call_soon(ensure_future(self._open_connection()))
+        ensure_future(self._open_connection())
 
     def _on_connect(self, transport):
         self._transport = transport
```

The problem appears to disappear with that change.

**Comment by sjlongland** [comment] 2022-07-31 03:55
```
tests/test_kiss/test_serial.py::test_send_raw_data 
------------------------------------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------------------------------------
ERROR    asyncio:base_events.py:1744 Exception in callback <Task pending name='Task-18' coro=<SerialKISSDevice._open_connection() running at /home/stuartl/projects/wicen/aioax25/aioax25/kiss.py:475> wait_for=<Future pending cb=[Task.task_wakeup()]>>()
handle: <Handle <Task pending name='Task-18' coro=<SerialKISSDevice._open_connection() running at /home/stuartl/projects/wicen/aioax25/aioax25/kiss.py:475> wait_for=<Future pending cb=[Task.task_wakeup()]>>()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
TypeError: '_asyncio.Task' object is not callable
PASSED   
```

Okay, that's on Ubuntu 22.04… so actually, it's not unique to MacOS X, which actually makes sense given the nature of how it's being caused.  Maybe by pure chance, we weren't seeing the errors due to inherent race-conditions between the log filtering in `py.test` and actual usage.

I haven't witnessed this in logs on Github's actions CI service or on my own laptop running Gentoo.  It would appear the port still opens, just it reports this annoying error which should still be fixed.

Reading up on `ensure_future`, it returns a `asyncio.Task` which is what we're seeing.  There's no methods or signals we can hook into for that task, so it would appear that just calling `ensure_future` is in fact, what we need to do… `call_soon` doesn't enter into it.

**Comment by sjlongland** [comment] 2022-07-31 04:03
https://github.com/sjlongland/aioax25/tree/bugfix/open-asyncio-task-not-callable has that change included.

**Comment by hemna** [comment] 2022-08-02 16:44
Looks like that branch has fixed that problem for me.  I have another issue, but I'll file a separate one for that.

**Comment by sjlongland** [comment] 2022-08-02 20:40
No problems, well, I've merged that branch into `master` now.  Onward with issue #13.

**Closed by sjlongland** 2022-08-02 20:40 UTC
